export const cardDetails = [
  {
    title: "Zeela",
    status: "Upcoming",
    type: "Fair launch",
    isFavorite: false,
    maxBuy: "0.02 BNB",
    softCap: 250,
    hardCap: 1000,
    progress: 0,
    liquidity: 51,
    lockTime: 365,
    saleStartDate: "00: 24: 16",
  },
  {
    title: "Zeela",
    status: "Upcoming",
    type: "Fair launch",
    isFavorite: true,
    maxBuy: "0.02 BNB",
    softCap: 250,
    hardCap: 1000,
    progress: 0,
    liquidity: 51,
    lockTime: 365,
    saleStartDate: "00: 24: 16",
  },
  {
    title: "Zeela",
    status: "Upcoming",
    type: "Fair launch",
    isFavorite: false,
    maxBuy: "0.02 BNB",
    softCap: 250,
    hardCap: 1000,
    progress: 0,
    liquidity: 51,
    lockTime: 365,
    saleStartDate: "00: 24: 16",
  },
  {
    title: "Zeela",
    status: "Ended",
    type: "Fair launch",
    isFavorite: true,
    maxBuy: "0.02 BNB",
    softCap: 250,
    hardCap: 1000,
    progress: 50,
    liquidity: 51,
    lockTime: 365,
    saleStartDate: "00: 24: 16",
  },
  {
    title: "Zeela",
    status: "Upcoming",
    type: "Fair launch",
    isFavorite: false,
    maxBuy: "0.02 BNB",
    softCap: 250,
    hardCap: 1000,
    progress: 0,
    liquidity: 51,
    lockTime: 365,
    saleStartDate: "00: 24: 16",
  },
  {
    title: "Zeela",
    status: "Upcoming",
    type: "Fair launch",
    isFavorite: true,
    maxBuy: "0.02 BNB",
    softCap: 250,
    hardCap: 1000,
    progress: 0,
    liquidity: 51,
    lockTime: 365,
    saleStartDate: "00: 24: 16",
  },
];
export const airdropListDetails = [
  {
    title: "SoliMax Airdrop",
    status: "Upcoming",
    tokenType: "Solimax",
    isFavorite: false,
    amountOfToken: "1,000,000 SLM",
    participants: 0,
    saleStartTime: "00: 24: 16",
  },
  {
    title: "SoliMax Airdrop",
    status: "Upcoming",
    tokenType: "Solimax",
    isFavorite: false,
    amountOfToken: "1,000,000 SLM",
    participants: 0,
    saleStartTime: "00: 24: 16",
  },
  {
    title: "SoliMax Airdrop",
    status: "Upcoming",
    tokenType: "Solimax",
    isFavorite: false,
    amountOfToken: "1,000,000 SLM",
    participants: 0,
    saleStartTime: "00: 24: 16",
  },
  {
    title: "SoliMax Airdrop",
    status: "Upcoming",
    tokenType: "Solimax",
    isFavorite: false,
    amountOfToken: "1,000,000 SLM",
    participants: 0,
    saleStartTime: "00: 24: 16",
  },
];



export const TrendingPoolsData = [
  {
    id: 1,
    projectName: "Cardashian",
    saleType: "Public",
    price: 10,
    minBuy: 100,
    maxBuy: 1000,
    totalSupply: 1000000,
    dateOfCompletion: "17th April, 10:00am UTC +1"
  },
  {
    id: 2,
    projectName: "Cardashian",
    saleType: "Public",
    price: 10,
    minBuy: 100,
    maxBuy: 1000,
    totalSupply: 1000000,
    dateOfCompletion: "17th April, 10:00am UTC +1"
  },
  {
    id: 3,
    projectName: "Cardashian",
    saleType: "Public",
    price: 10,
    minBuy: 100,
    maxBuy: 1000,
    totalSupply: 1000000,
    dateOfCompletion: "17th April, 10:00am UTC +1"
  },
  {
    id: 4,
    projectName: "Cardashian",
    saleType: "Public",
    price: 10,
    minBuy: 100,
    maxBuy: 1000,
    totalSupply: 1000000,
    dateOfCompletion: "17th April, 10:00am UTC +1"
  },
  {
    id: 5,
    projectName: "Cardashian",
    saleType: "Public",
    price: 10,
    minBuy: 100,
    maxBuy: 1000,
    totalSupply: 1000000,
    dateOfCompletion: "17th April, 10:00am UTC +1"
  },
]