export const cardDetails = [
    {
      title: "Zeela",
      status: "Upcoming",
      type: "Fair launch",
      isFavorite: false,
      maxBuy: "0.02 BNB",
      softCap: 250,
      hardCap: 1000,
      progress: 0,
      liquidity: 51,
      lockTime: 365,
      saleStartDate: "00: 24: 16",
    },
    {
      title: "Zeela",
      status: "Upcoming",
      type: "Fair launch",
      isFavorite: true,
      maxBuy: "0.02 BNB",
      softCap: 250,
      hardCap: 1000,
      progress: 0,
      liquidity: 51,
      lockTime: 365,
      saleStartDate: "00: 24: 16",
    },
    {
      title: "Zeela",
      status: "Upcoming",
      type: "Fair launch",
      isFavorite: false,
      maxBuy: "0.02 BNB",
      softCap: 250,
      hardCap: 1000,
      progress: 0,
      liquidity: 51,
      lockTime: 365,
      saleStartDate: "00: 24: 16",
    },
    {
      title: "Zeela",
      status: "Ended",
      type: "Fair launch",
      isFavorite: true,
      maxBuy: "0.02 BNB",
      softCap: 250,
      hardCap: 1000,
      progress: 50,
      liquidity: 51,
      lockTime: 365,
      saleStartDate: "00: 24: 16",
    },
    {
      title: "Zeela",
      status: "Upcoming",
      type: "Fair launch",
      isFavorite: false,
      maxBuy: "0.02 BNB",
      softCap: 250,
      hardCap: 1000,
      progress: 0,
      liquidity: 51,
      lockTime: 365,
      saleStartDate: "00: 24: 16",
    },
    {
      title: "Zeela",
      status: "Upcoming",
      type: "Fair launch",
      isFavorite: true,
      maxBuy: "0.02 BNB",
      softCap: 250,
      hardCap: 1000,
      progress: 0,
      liquidity: 51,
      lockTime: 365,
      saleStartDate: "00: 24: 16",
    },
  ];